# Generated by Django 4.2.6 on 2023-10-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='listing',
            field=models.CharField(max_length=200),
        ),
    ]
